import { Product } from "./types";

export const PRODUCTS: Product[] = [
  {
    id: 1,
    slug: "keeus-volt-runner",
    name: "Keeus Volt Runner",
    category: "unissex",
    price: 549.9,
    installmentPrice: 183.3,
    installments: 3,
    stock: 4,
    isLowStock: true,
    isNew: true,
    isLimitedEdition: false,
    sizes: [37, 38, 39, 40, 41, 42, 43],
    colors: ["#0a0a0b", "#d8ff4f", "#f5f5f1"],
    description:
      "Construção em malha respirável com entressola de espuma responsiva — feito para quem não desacelera.",
    image: "/products/keeus-volt-runner/cover.jpg",
    gallery: [
      "/products/keeus-volt-runner/01.jpg",
      "/products/keeus-volt-runner/02.jpg",
      "/products/keeus-volt-runner/03.jpg",
    ],
    angleCount: 12,
  },
  {
    id: 2,
    slug: "keeus-aero-slip",
    name: "Keeus Aero Slip",
    category: "feminino",
    price: 429.9,
    installmentPrice: 143.3,
    installments: 3,
    stock: 18,
    isLowStock: false,
    isNew: true,
    isLimitedEdition: false,
    sizes: [34, 35, 36, 37, 38, 39],
    colors: ["#f5f5f1", "#5b8cff"],
    description:
      "Slip-on sem cadarço com sistema de encaixe adaptativo — calça em 3 segundos, acompanha o dia todo.",
    image: "/products/keeus-aero-slip/cover.jpg",
    gallery: [
      "/products/keeus-aero-slip/01.jpg",
      "/products/keeus-aero-slip/02.jpg",
    ],
    angleCount: 12,
  },
  {
    id: 3,
    slug: "keeus-urban-strike",
    name: "Keeus Urban Strike",
    category: "masculino",
    price: 629.9,
    installmentPrice: 209.97,
    installments: 3,
    stock: 2,
    isLowStock: true,
    isNew: false,
    isLimitedEdition: true,
    sizes: [39, 40, 41, 42, 43, 44],
    colors: ["#0a0a0b", "#93939c"],
    description:
      "Edição limitada com solado de tração reforçada e couro reciclado certificado. Apenas 2 pares em estoque.",
    image: "/products/keeus-urban-strike/cover.jpg",
    gallery: [
      "/products/keeus-urban-strike/01.jpg",
      "/products/keeus-urban-strike/02.jpg",
    ],
    angleCount: 12,
  },
  {
    id: 4,
    slug: "keeus-cloud-step",
    name: "Keeus Cloud Step",
    category: "feminino",
    price: 389.9,
    installmentPrice: 129.97,
    installments: 3,
    stock: 25,
    isLowStock: false,
    isNew: false,
    isLimitedEdition: false,
    sizes: [34, 35, 36, 37, 38, 39, 40],
    colors: ["#f5f5f1", "#d8ff4f"],
    description:
      "Amortecimento em gel de dupla camada para quem fica em pé o dia inteiro sem abrir mão do estilo.",
    image: "/products/keeus-cloud-step/cover.jpg",
    gallery: [
      "/products/keeus-cloud-step/01.jpg",
      "/products/keeus-cloud-step/02.jpg",
    ],
    angleCount: 12,
  },
  {
    id: 5,
    slug: "keeus-grid-trail",
    name: "Keeus Grid Trail",
    category: "masculino",
    price: 599.9,
    installmentPrice: 199.97,
    installments: 3,
    stock: 11,
    isLowStock: false,
    isNew: false,
    isLimitedEdition: false,
    sizes: [39, 40, 41, 42, 43, 44, 45],
    colors: ["#0a0a0b", "#5b8cff"],
    description:
      "Tração off-road com cabedal impermeável — para quem não escolhe entre cidade e trilha.",
    image: "/products/keeus-grid-trail/cover.jpg",
    gallery: [
      "/products/keeus-grid-trail/01.jpg",
      "/products/keeus-grid-trail/02.jpg",
    ],
    angleCount: 12,
  },
  {
    id: 6,
    slug: "keeus-nova-knit",
    name: "Keeus Nova Knit",
    category: "unissex",
    price: 479.9,
    installmentPrice: 159.97,
    installments: 3,
    stock: 7,
    isLowStock: true,
    isNew: true,
    isLimitedEdition: false,
    sizes: [36, 37, 38, 39, 40, 41, 42],
    colors: ["#d8ff4f", "#0a0a0b"],
    description:
      "Tricô 3D de fio único, zero costura interna — sensação de segunda pele em qualquer movimento.",
    image: "/products/keeus-nova-knit/cover.jpg",
    gallery: [
      "/products/keeus-nova-knit/01.jpg",
      "/products/keeus-nova-knit/02.jpg",
    ],
    angleCount: 12,
  },
];

export const getProductBySlug = (slug: string) =>
  PRODUCTS.find((p) => p.slug === slug);
