import { Product } from "./types";

export const PRODUCTS: Product[] = [
  // ── NIKE ──────────────────────────────────────────────────────────
  {
    id: 1,
    slug: "nike-mercurial-superfly",
    name: "Nike Mercurial Superfly 9",
    category: "campo",
    brand: "Nike",
    price: 999.9,
    installmentPrice: 166.65,
    installments: 6,
    stock: 15,
    isLowStock: false,
    isNew: true,
    isLimitedEdition: false,
    sizes: [37, 38, 39, 40, 41, 42, 43, 44],
    colors: ["#FFD700", "#0a0a0b"],
    description:
      "A Mercurial Superfly 9 é feita para velocidade máxima em campo. Cabedal Flyknit com revestimento Gripknit que oferece controle de bola preciso e sensação de pé descalço.",
    image: "/products/placeholder.svg",
    gallery: ["/products/placeholder.svg"],
    angleCount: 1,
  },
  {
    id: 2,
    slug: "nike-tiempo-legend",
    name: "Nike Tiempo Legend 10",
    category: "campo",
    brand: "Nike",
    price: 899.9,
    installmentPrice: 149.98,
    installments: 6,
    stock: 12,
    isLowStock: false,
    isNew: false,
    isLimitedEdition: false,
    sizes: [37, 38, 39, 40, 41, 42, 43, 44],
    colors: ["#FFFFFF", "#0a0a0b"],
    description:
      "Tradição e toque refinado. A Tiempo Legend 10 combina couro premium FlyTouch Pro com amortecimento em espuma ultramacia. Conforto clássico com tecnologia moderna para quem pensa o jogo.",
    image: "/products/placeholder.svg",
    gallery: ["/products/placeholder.svg"],
    angleCount: 1,
  },
  // ── ADIDAS ────────────────────────────────────────────────────────
  {
    id: 3,
    slug: "adidas-predator-accuracy",
    name: "Adidas Predator Accuracy.1",
    category: "campo",
    brand: "Adidas",
    price: 1099.9,
    installmentPrice: 183.32,
    installments: 6,
    stock: 8,
    isLowStock: false,
    isNew: true,
    isLimitedEdition: false,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    colors: ["#FF0000", "#0a0a0b"],
    description:
      "Quando o gol está nos seus pés. A Predator Accuracy.1 traz elementos de borracha High Definition Grip no cabedal para efeito e precisão nos chutes. Solado com travas estratégicas para máxima tração.",
    image: "/products/placeholder.svg",
    gallery: ["/products/placeholder.svg"],
    angleCount: 1,
  },
  {
    id: 4,
    slug: "adidas-copa-pure",
    name: "Adidas Copa Pure II",
    category: "society",
    brand: "Adidas",
    price: 649.9,
    installmentPrice: 108.32,
    installments: 6,
    stock: 20,
    isLowStock: false,
    isNew: false,
    isLimitedEdition: false,
    sizes: [34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
    colors: ["#0a0a0b", "#FFFFFF"],
    description:
      "A pureza do futebol no seu pé. Cabedal em couro macio que se molda ao formato do pé com o uso. Ideal para society, com solado de borracha especial para grama sintética. Conforto que dura o jogo inteiro.",
    image: "/products/placeholder.svg",
    gallery: ["/products/placeholder.svg"],
    angleCount: 1,
  },
  // ── PUMA ─────────────────────────────────────────────────────────
  {
    id: 5,
    slug: "puma-future-ultimate",
    name: "Puma Future Ultimate",
    category: "society",
    brand: "Puma",
    price: 799.9,
    installmentPrice: 133.32,
    installments: 6,
    stock: 10,
    isLowStock: false,
    isNew: true,
    isLimitedEdition: false,
    sizes: [37, 38, 39, 40, 41, 42, 43],
    colors: ["#00A3E0", "#0a0a0b"],
    description:
      "Ajuste adaptável que abraça o pé. Tecnologia FUZIONFIT360 com malha elástica que se expande e contrai conforme o movimento. Perfeita para jogadores que mudam de direção constantemente.",
    image: "/products/placeholder.svg",
    gallery: ["/products/placeholder.svg"],
    angleCount: 1,
  },
  {
    id: 6,
    slug: "puma-king-ultimate",
    name: "Puma King Ultimate",
    category: "campo",
    brand: "Puma",
    price: 729.9,
    installmentPrice: 121.65,
    installments: 6,
    stock: 6,
    isLowStock: true,
    isNew: false,
    isLimitedEdition: false,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    colors: ["#0a0a0b", "#FFFFFF"],
    description:
      "A realeza do futebol. King Ultimate combina couro K-BETTER supermacio com entressola leve e responsiva. Construção clássica com performance moderna para os camisas 10 de hoje.",
    image: "/products/placeholder.svg",
    gallery: ["/products/placeholder.svg"],
    angleCount: 1,
  },
  // ── MIZUNO ───────────────────────────────────────────────────────
  {
    id: 7,
    slug: "mizuno-morelia-neo-iv",
    name: "Mizuno Morelia Neo IV",
    category: "campo",
    brand: "Mizuno",
    price: 1299.9,
    installmentPrice: 216.65,
    installments: 6,
    stock: 4,
    isLowStock: true,
    isNew: true,
    isLimitedEdition: false,
    sizes: [38, 39, 40, 41, 42, 43],
    colors: ["#FFFFFF", "#E60012"],
    description:
      "A obra-prima japonesa. Couro de canguru legítimo selecionado à mão, costurado artesanalmente no Japão. Peso de apenas 195g com ajuste anatômico perfeito. A escolha de quem valoriza o toque de bola impecável.",
    image: "/products/placeholder.svg",
    gallery: ["/products/placeholder.svg"],
    angleCount: 1,
  },
  {
    id: 8,
    slug: "mizuno-monarcida-neo-iii",
    name: "Mizuno Monarcida Neo III",
    category: "society",
    brand: "Mizuno",
    price: 549.9,
    installmentPrice: 91.65,
    installments: 6,
    stock: 18,
    isLowStock: false,
    isNew: false,
    isLimitedEdition: false,
    sizes: [35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
    colors: ["#0a0a0b", "#FFD700"],
    description:
      "Conforto japonês para grama sintética. Cabedal em couro sintético premium com reforço na zona de contato. Palmilha removível e solado próprio para society. Ótimo custo-benefício Mizuno.",
    image: "/products/placeholder.svg",
    gallery: ["/products/placeholder.svg"],
    angleCount: 1,
  },
  // ── UMBRO ────────────────────────────────────────────────────────
  {
    id: 9,
    slug: "umbro-neo-pro",
    name: "Umbro Neo Pro",
    category: "futsal",
    brand: "Umbro",
    price: 349.9,
    installmentPrice: 87.48,
    installments: 4,
    stock: 25,
    isLowStock: false,
    isNew: true,
    isLimitedEdition: false,
    sizes: [33, 34, 35, 36, 37, 38, 39, 40, 41, 42],
    colors: ["#0a0a0b", "#FF6A00"],
    description:
      "Domínio total na quadra. Cabedal em mesh respirável com reforço sintético nas áreas de maior desgaste. Solado de borracha non-marking com perfil baixo para máxima aderência em piso de quadra.",
    image: "/products/placeholder.svg",
    gallery: ["/products/placeholder.svg"],
    angleCount: 1,
  },
  {
    id: 10,
    slug: "umbro-tocco-iii",
    name: "Umbro Tocco III",
    category: "futsal",
    brand: "Umbro",
    price: 279.9,
    installmentPrice: 69.98,
    installments: 4,
    stock: 30,
    isLowStock: false,
    isNew: false,
    isLimitedEdition: false,
    sizes: [33, 34, 35, 36, 37, 38, 39, 40, 41],
    colors: ["#FFFFFF", "#003399"],
    description:
      "Toque suave, controle total. A Tocco III traz cabedal com zonas de toque texturizadas que melhoram o domínio de bola. Entressola em EVA para amortecimento durante o jogo de quadra. Leve e confortável.",
    image: "/products/placeholder.svg",
    gallery: ["/products/placeholder.svg"],
    angleCount: 1,
  },
  // ── PENALTY ─────────────────────────────────────────────────────
  {
    id: 11,
    slug: "penalty-s11-pro",
    name: "Penalty S11 Pro",
    category: "society",
    brand: "Penalty",
    price: 229.9,
    installmentPrice: 57.48,
    installments: 4,
    stock: 35,
    isLowStock: false,
    isNew: true,
    isLimitedEdition: false,
    sizes: [34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
    colors: ["#0a0a0b", "#00B341"],
    description:
      "Brasileira de raiz, acessível e eficiente. Cabedal sintético resistente com costuras reforçadas. Solado multidirecional para society com excelente tração. A escolha inteligente para quem joga toda semana.",
    image: "/products/placeholder.svg",
    gallery: ["/products/placeholder.svg"],
    angleCount: 1,
  },
  {
    id: 12,
    slug: "penalty-max-1000",
    name: "Penalty Max 1000",
    category: "campo",
    brand: "Penalty",
    price: 179.9,
    installmentPrice: 44.98,
    installments: 4,
    stock: 40,
    isLowStock: false,
    isNew: false,
    isLimitedEdition: false,
    sizes: [34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
    colors: ["#FFFFFF", "#E60012"],
    description:
      "Entrada no futebol de campo com qualidade. Cabedal em PU resistente à abrasão, solado com travas moldadas em TPU. Ideal para quem está começando ou joga em campos de terra e grama baixa. Custo imbatível.",
    image: "/products/placeholder.svg",
    gallery: ["/products/placeholder.svg"],
    angleCount: 1,
  },
  // ══════════════════════════════════════════════════════════════════
  // ── KEEUS CHINELOS PREMIUM ─────────────────────────────────────
  // ══════════════════════════════════════════════════════════════════
  {
    id: 13,
    slug: "keeus-slide-pro-laranja",
    name: "Keeus Slide Pro Laranja",
    category: "chinelo",
    brand: "Keeus",
    price: 149.9,
    installmentPrice: 37.48,
    installments: 4,
    stock: 50,
    isLowStock: false,
    isNew: true,
    isLimitedEdition: false,
    sizes: [35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
    colors: ["#FF5F00", "#0a0a0b"],
    description:
      "O chinelo que respira futebol. Slide Pro Laranja com palmilha em EVA de alta densidade, solado antiderrapante e design inspirado no universo das chuteiras. Conforto do vestiário para a rua.",
    image: "/products/placeholder.svg",
    gallery: ["/products/placeholder.svg"],
    angleCount: 1,
    originalPrice: 179.9,
  },
  {
    id: 14,
    slug: "keeus-slide-pro-preto",
    name: "Keeus Slide Pro Preto",
    category: "chinelo",
    brand: "Keeus",
    price: 149.9,
    installmentPrice: 37.48,
    installments: 4,
    stock: 45,
    isLowStock: false,
    isNew: true,
    isLimitedEdition: false,
    sizes: [35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
    colors: ["#0a0a0b", "#FF5F00"],
    description:
      "Discrição e estilo no pós-jogo. Slide Pro Preto com faixa em laranja Keeus, palmilha ortopédica em EVA e solado em borracha premium. O parceiro ideal depois da partida.",
    image: "/products/placeholder.svg",
    gallery: ["/products/placeholder.svg"],
    angleCount: 1,
  },
  {
    id: 15,
    slug: "keeus-flip-summer-laranja",
    name: "Keeus Flip Summer Laranja",
    category: "chinelo",
    brand: "Keeus",
    price: 99.9,
    installmentPrice: 24.98,
    installments: 4,
    stock: 80,
    isLowStock: false,
    isNew: true,
    isLimitedEdition: false,
    sizes: [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
    colors: ["#FF5F00", "#FFFFFF"],
    description:
      "Verão é Keeus. Flip Summer com tiras em TPU flexível, palmilha anatômica que abraça o pé e estampa exclusiva com a identidade laranja. Leve como um drible, confortável como um gol.",
    image: "/products/placeholder.svg",
    gallery: ["/products/placeholder.svg"],
    angleCount: 1,
    originalPrice: 129.9,
  },
  {
    id: 16,
    slug: "keeus-flip-summer-branco",
    name: "Keeus Flip Summer Branco",
    category: "chinelo",
    brand: "Keeus",
    price: 99.9,
    installmentPrice: 24.98,
    installments: 4,
    stock: 70,
    isLowStock: false,
    isNew: false,
    isLimitedEdition: false,
    sizes: [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
    colors: ["#FFFFFF", "#FF5F00"],
    description:
      "Clean, fresh, Keeus. Flip Summer Branco com detalhes laranja, tiras ergonômicas e sola em borracha natural. Para usar da praia ao churrasco pós-futebol.",
    image: "/products/placeholder.svg",
    gallery: ["/products/placeholder.svg"],
    angleCount: 1,
  },
  {
    id: 17,
    slug: "keeus-cloud-laranja",
    name: "Keeus Cloud Laranja",
    category: "chinelo",
    brand: "Keeus",
    price: 179.9,
    installmentPrice: 44.98,
    installments: 4,
    stock: 30,
    isLowStock: false,
    isNew: true,
    isLimitedEdition: true,
    sizes: [37, 38, 39, 40, 41, 42, 43, 44],
    colors: ["#FF5F00"],
    description:
      "Edição limitada — sentir uma nuvem nos pés. Cloud Laranja com tecnologia memory foam em 3 camadas, solado ultra-amortecido e acabamento premium. Exclusivo Keeus, numerado na palmilha.",
    image: "/products/placeholder.svg",
    gallery: ["/products/placeholder.svg"],
    angleCount: 1,
  },
  {
    id: 18,
    slug: "keeus-cloud-preto",
    name: "Keeus Cloud Preto",
    category: "chinelo",
    brand: "Keeus",
    price: 179.9,
    installmentPrice: 44.98,
    installments: 4,
    stock: 25,
    isLowStock: true,
    isNew: true,
    isLimitedEdition: true,
    sizes: [37, 38, 39, 40, 41, 42, 43, 44],
    colors: ["#0a0a0b", "#FF5F00"],
    description:
      "Sofisticação encontra conforto. Cloud Preto com detalhes laranja fantasma, tecnologia memory foam tripla camada, e palmilha numerada. Edição limitadíssima — restam poucas unidades.",
    image: "/products/placeholder.svg",
    gallery: ["/products/placeholder.svg"],
    angleCount: 1,
  },
  {
    id: 19,
    slug: "keeus-sport-slide-mesh",
    name: "Keeus Sport Slide Mesh",
    category: "chinelo",
    brand: "Keeus",
    price: 129.9,
    installmentPrice: 32.48,
    installments: 4,
    stock: 60,
    isLowStock: false,
    isNew: false,
    isLimitedEdition: false,
    sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
    colors: ["#0a0a0b", "#FF5F00"],
    description:
      "Do vestiário direto pro rolê. Sport Slide com faixa em mesh respirável, palmilha antimicrobiana e solado de alta tração. Seca rápido, não escorrega, não deforma.",
    image: "/products/placeholder.svg",
    gallery: ["/products/placeholder.svg"],
    angleCount: 1,
  },
  {
    id: 20,
    slug: "keeus-street-laranja-neon",
    name: "Keeus Street Laranja Neon",
    category: "chinelo",
    brand: "Keeus",
    price: 89.9,
    installmentPrice: 22.48,
    installments: 4,
    stock: 100,
    isLowStock: false,
    isNew: true,
    isLimitedEdition: false,
    sizes: [34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
    colors: ["#FF5F00", "#0a0a0b"],
    description:
      "A rua é o campo. Street Laranja Neon — chinelo de dedo com solado robusto, tira larga em TPU e a cor que ninguém ignora. Para quem joga o dia a dia com atitude.",
    image: "/products/placeholder.svg",
    gallery: ["/products/placeholder.svg"],
    angleCount: 1,
    originalPrice: 109.9,
  },
  {
    id: 21,
    slug: "keeus-street-preto-basico",
    name: "Keeus Street Preto Básico",
    category: "chinelo",
    brand: "Keeus",
    price: 79.9,
    installmentPrice: 19.98,
    installments: 4,
    stock: 120,
    isLowStock: false,
    isNew: false,
    isLimitedEdition: false,
    sizes: [34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
    colors: ["#0a0a0b"],
    description:
      "Básico só no nome. Street Preto com detalhes em laranja minimalista, solado em EVA de longa duração e tira em TPU resistente. O chinelo que acompanha toda jornada — do campo ao rolê.",
    image: "/products/placeholder.svg",
    gallery: ["/products/placeholder.svg"],
    angleCount: 1,
  },
  // ── ROBERTO ───────────────────────────────────────────────────────
  {
    id: 22,
    slug: "roberto",
    name: "Roberto Pro Elite Campo",
    category: "campo",
    brand: "Roberto",
    price: 459.9,
    installmentPrice: 76.65,
    installments: 6,
    stock: 12,
    isLowStock: false,
    isNew: true,
    isLimitedEdition: false,
    sizes: [37, 38, 39, 40, 41, 42, 43],
    colors: ["#FF5F00", "#0a0a0b"],
    description:
      "Nova marca brasileira que chegou pra ficar. A Roberto Pro Elite traz cabedal em microfiber premium com tecnologia de ajuste térmico, palmilha ergonômica e solado com travas cônicas. Performance de elite com preço justo — o equilíbrio que o futebol brasileiro merece.",
    image: "/products/roberto.jpg",
    gallery: ["/products/roberto.jpg"],
    angleCount: 1,
  },
];

export const getProductBySlug = (slug: string) =>
  PRODUCTS.find((p) => p.slug === slug);

export const getFeaturedProducts = () => PRODUCTS.slice(0, 6);

export const getNewArrivals = () => PRODUCTS.filter((p) => p.isNew);

export const getProductsByCategory = (category: Product["category"]) =>
  PRODUCTS.filter((p) => p.category === category);

export const getChinelos = () => PRODUCTS.filter((p) => p.category === "chinelo");
