import { Product } from "./types";

export const PRODUCTS: Product[] = [
  // ── NIKE ──────────────────────────────────────────────────────────
  {
    id: 1,
    slug: "nike-mercurial-superfly",
    name: "Nike Mercurial Superfly 9",
    category: "campo",
    brand: "Nike",
    price: 999.9,
    installmentPrice: 166.65,
    installments: 6,
    stock: 15,
    isLowStock: false,
    isNew: true,
    isLimitedEdition: false,
    sizes: [37, 38, 39, 40, 41, 42, 43, 44],
    colors: ["#FFD700", "#0a0a0b"],
    description:
      "A Mercurial Superfly 9 é feita para velocidade máxima em campo. Cabedal Flyknit com revestimento Gripknit que oferece controle de bola preciso e sensação de pé descalço.",
    image: "/products/placeholder.svg",
    gallery: ["/products/placeholder.svg"],
    angleCount: 1,
  },
  {
    id: 2,
    slug: "nike-tiempo-legend",
    name: "Nike Tiempo Legend 10",
    category: "campo",
    brand: "Nike",
    price: 899.9,
    installmentPrice: 149.98,
    installments: 6,
    stock: 12,
    isLowStock: false,
    isNew: false,
    isLimitedEdition: false,
    sizes: [37, 38, 39, 40, 41, 42, 43, 44],
    colors: ["#FFFFFF", "#0a0a0b"],
    description:
      "Tradição e toque refinado. A Tiempo Legend 10 combina couro premium FlyTouch Pro com amortecimento em espuma ultramacia. Conforto clássico com tecnologia moderna para quem pensa o jogo.",
    image: "/products/placeholder.svg",
    gallery: ["/products/placeholder.svg"],
    angleCount: 1,
  },
  // ── ADIDAS ────────────────────────────────────────────────────────
  {
    id: 3,
    slug: "adidas-predator-accuracy",
    name: "Adidas Predator Accuracy.1",
    category: "campo",
    brand: "Adidas",
    price: 1099.9,
    installmentPrice: 183.32,
    installments: 6,
    stock: 8,
    isLowStock: false,
    isNew: true,
    isLimitedEdition: false,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    colors: ["#FF0000", "#0a0a0b"],
    description:
      "Quando o gol está nos seus pés. A Predator Accuracy.1 traz elementos de borracha High Definition Grip no cabedal para efeito e precisão nos chutes. Solado com travas estratégicas para máxima tração.",
    image: "/products/placeholder.svg",
    gallery: ["/products/placeholder.svg"],
    angleCount: 1,
  },
  {
    id: 4,
    slug: "adidas-copa-pure",
    name: "Adidas Copa Pure II",
    category: "society",
    brand: "Adidas",
    price: 649.9,
    installmentPrice: 108.32,
    installments: 6,
    stock: 20,
    isLowStock: false,
    isNew: false,
    isLimitedEdition: false,
    sizes: [34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
    colors: ["#0a0a0b", "#FFFFFF"],
    description:
      "A pureza do futebol no seu pé. Cabedal em couro macio que se molda ao formato do pé com o uso. Ideal para society, com solado de borracha especial para grama sintética. Conforto que dura o jogo inteiro.",
    image: "/products/placeholder.svg",
    gallery: ["/products/placeholder.svg"],
    angleCount: 1,
  },
  // ── PUMA ─────────────────────────────────────────────────────────
  {
    id: 5,
    slug: "puma-future-ultimate",
    name: "Puma Future Ultimate",
    category: "society",
    brand: "Puma",
    price: 799.9,
    installmentPrice: 133.32,
    installments: 6,
    stock: 10,
    isLowStock: false,
    isNew: true,
    isLimitedEdition: false,
    sizes: [37, 38, 39, 40, 41, 42, 43],
    colors: ["#00A3E0", "#0a0a0b"],
    description:
      "Ajuste adaptável que abraça o pé. Tecnologia FUZIONFIT360 com malha elástica que se expande e contrai conforme o movimento. Perfeita para jogadores que mudam de direção constantemente.",
    image: "/products/placeholder.svg",
    gallery: ["/products/placeholder.svg"],
    angleCount: 1,
  },
  {
    id: 6,
    slug: "puma-king-ultimate",
    name: "Puma King Ultimate",
    category: "campo",
    brand: "Puma",
    price: 729.9,
    installmentPrice: 121.65,
    installments: 6,
    stock: 6,
    isLowStock: true,
    isNew: false,
    isLimitedEdition: false,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    colors: ["#0a0a0b", "#FFFFFF"],
    description:
      "A realeza do futebol. King Ultimate combina couro K-BETTER supermacio com entressola leve e responsiva. Construção clássica com performance moderna para os camisas 10 de hoje.",
    image: "/products/placeholder.svg",
    gallery: ["/products/placeholder.svg"],
    angleCount: 1,
  },
  // ── MIZUNO ───────────────────────────────────────────────────────
  {
    id: 7,
    slug: "mizuno-morelia-neo-iv",
    name: "Mizuno Morelia Neo IV",
    category: "campo",
    brand: "Mizuno",
    price: 1299.9,
    installmentPrice: 216.65,
    installments: 6,
    stock: 4,
    isLowStock: true,
    isNew: true,
    isLimitedEdition: false,
    sizes: [38, 39, 40, 41, 42, 43],
    colors: ["#FFFFFF", "#E60012"],
    description:
      "A obra-prima japonesa. Couro de canguru legítimo selecionado à mão, costurado artesanalmente no Japão. Peso de apenas 195g com ajuste anatômico perfeito. A escolha de quem valoriza o toque de bola impecável.",
    image: "/products/placeholder.svg",
    gallery: ["/products/placeholder.svg"],
    angleCount: 1,
  },
  {
    id: 8,
    slug: "mizuno-monarcida-neo-iii",
    name: "Mizuno Monarcida Neo III",
    category: "society",
    brand: "Mizuno",
    price: 549.9,
    installmentPrice: 91.65,
    installments: 6,
    stock: 18,
    isLowStock: false,
    isNew: false,
    isLimitedEdition: false,
    sizes: [35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
    colors: ["#0a0a0b", "#FFD700"],
    description:
      "Conforto japonês para grama sintética. Cabedal em couro sintético premium com reforço na zona de contato. Palmilha removível e solado próprio para society. Ótimo custo-benefício Mizuno.",
    image: "/products/placeholder.svg",
    gallery: ["/products/placeholder.svg"],
    angleCount: 1,
  },
  // ── UMBRO ────────────────────────────────────────────────────────
  {
    id: 9,
    slug: "umbro-neo-pro",
    name: "Umbro Neo Pro",
    category: "futsal",
    brand: "Umbro",
    price: 349.9,
    installmentPrice: 87.48,
    installments: 4,
    stock: 25,
    isLowStock: false,
    isNew: true,
    isLimitedEdition: false,
    sizes: [33, 34, 35, 36, 37, 38, 39, 40, 41, 42],
    colors: ["#0a0a0b", "#FF6A00"],
    description:
      "Domínio total na quadra. Cabedal em mesh respirável com reforço sintético nas áreas de maior desgaste. Solado de borracha non-marking com perfil baixo para máxima aderência em piso de quadra.",
    image: "/products/placeholder.svg",
    gallery: ["/products/placeholder.svg"],
    angleCount: 1,
  },
  {
    id: 10,
    slug: "umbro-tocco-iii",
    name: "Umbro Tocco III",
    category: "futsal",
    brand: "Umbro",
    price: 279.9,
    installmentPrice: 69.98,
    installments: 4,
    stock: 30,
    isLowStock: false,
    isNew: false,
    isLimitedEdition: false,
    sizes: [33, 34, 35, 36, 37, 38, 39, 40, 41],
    colors: ["#FFFFFF", "#003399"],
    description:
      "Toque suave, controle total. A Tocco III traz cabedal com zonas de toque texturizadas que melhoram o domínio de bola. Entressola em EVA para amortecimento durante o jogo de quadra. Leve e confortável.",
    image: "/products/placeholder.svg",
    gallery: ["/products/placeholder.svg"],
    angleCount: 1,
  },
  // ── PENALTY ─────────────────────────────────────────────────────
  {
    id: 11,
    slug: "penalty-s11-pro",
    name: "Penalty S11 Pro",
    category: "society",
    brand: "Penalty",
    price: 229.9,
    installmentPrice: 57.48,
    installments: 4,
    stock: 35,
    isLowStock: false,
    isNew: true,
    isLimitedEdition: false,
    sizes: [34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
    colors: ["#0a0a0b", "#00B341"],
    description:
      "Brasileira de raiz, acessível e eficiente. Cabedal sintético resistente com costuras reforçadas. Solado multidirecional para society com excelente tração. A escolha inteligente para quem joga toda semana.",
    image: "/products/placeholder.svg",
    gallery: ["/products/placeholder.svg"],
    angleCount: 1,
  },
  {
    id: 12,
    slug: "penalty-max-1000",
    name: "Penalty Max 1000",
    category: "campo",
    brand: "Penalty",
    price: 179.9,
    installmentPrice: 44.98,
    installments: 4,
    stock: 40,
    isLowStock: false,
    isNew: false,
    isLimitedEdition: false,
    sizes: [34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
    colors: ["#FFFFFF", "#E60012"],
    description:
      "Entrada no futebol de campo com qualidade. Cabedal em PU resistente à abrasão, solado com travas moldadas em TPU. Ideal para quem está começando ou joga em campos de terra e grama baixa. Custo imbatível.",
    image: "/products/placeholder.svg",
    gallery: ["/products/placeholder.svg"],
    angleCount: 1,
  },
];

export const getProductBySlug = (slug: string) =>
  PRODUCTS.find((p) => p.slug === slug);

export const getFeaturedProducts = () => PRODUCTS.slice(0, 6);

export const getNewArrivals = () => PRODUCTS.filter((p) => p.isNew);

export const getProductsByCategory = (category: Product["category"]) =>
  PRODUCTS.filter((p) => p.category === category);
